## What is numpy?

NumPy (short for Numerical Python) is a fundamental Python library for scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a vast collection of high-level mathematical functions to operate on these arrays efficiently.

## Numpy vs Python Sequences

- Numpy optimized in C (100x faster), supports vectorized operations (no loops). Lists slower (Python-interpreted), requires loops for math operations.
- NumPy homogeneous (fixed dtype), contiguous memory (efficient for large data). Lists heterogeneous (mixed types), dynamic but memory-heavy (stores pointers).
- NumPy built-in math (np.sin(), np.dot()), broadcasting, multi-dimensional support. Lists no native math ops, no broadcasting, only 1D (nested lists are messy).
- NumPy numerical computing (ML/data science), large datasets, matrix operations. Lists general-purpose tasks, mixed data types, frequent resizing (append/pop).

In [273]:
## Import numpy
import numpy as np

In [274]:
## 1D Array (Vector)
arr1 = np.array([1,2,3,4])

print(arr1)

[1 2 3 4]


In [275]:
## 2D Array (Matrix)
arr2 = np.array([[1,2,3,4], [5,6,7,8]])

print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [276]:
## 3D Array (Tensors)
arr3 = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [5,6,7,8]]])

print(arr3)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [277]:
## type
type(arr1)

numpy.ndarray

In [278]:
## dtype
d_type = np.array([1,2,3,4,5], dtype=float)

print(d_type)

[1. 2. 3. 4. 5.]


In [279]:
##  np.arrange
_arange = np.arange(1, 100, 5)

In [280]:
## with reshape
_arange.reshape(4,5)

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46],
       [51, 56, 61, 66, 71],
       [76, 81, 86, 91, 96]])

In [281]:
## np.ones 
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [282]:
## np.zeros
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [283]:
## np.random
np.random.random((3,4))

array([[0.70699483, 0.67016302, 0.07969377, 0.82408248],
       [0.83973056, 0.07071691, 0.17828973, 0.42648464],
       [0.29182944, 0.98900974, 0.5988455 , 0.9924178 ]])

In [284]:
## np.linspace
np.linspace(-10,10,5)

array([-10.,  -5.,   0.,   5.,  10.])

In [285]:
## np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Attributes

In [286]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [287]:
## ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [288]:
## shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [289]:
## size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [290]:
## dtype
a1.dtype

dtype('int32')

## Changing Datatypes

In [291]:
## astype
a1.astype(np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

## Array Operations

In [292]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [293]:
## Scalar Operations
## arithmetiic
a4**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [294]:
## relational
a4 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [295]:
## Vector Operations
## arithmetic
a4 + a5

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

## Array Functions

In [296]:
a6 = np.random.random((3,3))
a6 = np.round(a6*100)
a6

array([[27., 77., 76.],
       [51., 45., 32.],
       [40., 62., 44.]])

In [297]:
## max
## 0 -> col and 1 -> row
np.max(a6, axis=0)

array([51., 77., 76.])

In [298]:
## min
np.min(a6, axis=1)

array([27., 32., 40.])

In [299]:
## prod
np.prod(a6, axis=1)

array([158004.,  73440., 109120.])

In [300]:
## mean
np.mean(a6)

50.44444444444444

In [301]:
## median
np.median(a6)

45.0

In [302]:
## standard deviation
np.std(a6)

16.87279935353619

In [303]:
## variance
np.var(a6)

284.69135802469134

In [304]:
## dot product
a7 = np.arange(12).reshape(3,4)
a8 = np.arange(12,24).reshape(4,3)

np.dot(a7, a8)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [305]:
## log 
np.log(a7)

C:\Users\Tanjim Ahmed\AppData\Local\Temp\ipykernel_13216\2825401904.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a7)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [306]:
## exponents
np.exp(a8)

array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [307]:
## round
np.round(np.random.random(10)*100)

array([ 6., 84., 41., 89., 80., 90., 73., 77., 91., 61.])

In [308]:
## floor
np.floor(np.random.random(10)*100)

array([82., 90., 77., 62.,  2., 72., 93., 11., 30., 98.])

In [309]:
## ceil
np.ceil(np.random.random(10)*100)

array([ 80., 100.,  90.,  81.,   5.,  48.,  98.,  95.,  52.,  58.])

## Indexing and Slicing

In [310]:
a9 = np.arange(10)
a10 = np.arange(12, dtype=float).reshape(3,4)
a11 = np.arange(27).reshape(3,3,3)

In [311]:
## 1D Array Indexing
print(a9)
print(a9[2])

[0 1 2 3 4 5 6 7 8 9]
2


In [312]:
## 1D Array Reverse Indexing
print(a9[-1])

9


In [313]:
## 2D Array Indexing
print(a10)
print(a10[2,2])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
10.0


In [314]:
## 3D Array Indexing
print(a11)
print(a11[1,0,1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
10


In [315]:
## 1D Array Slicing
print(a9)
print(a9[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [316]:
## 1D Array Reverse Slicing
print(a9[-1:-4:-1])

[9 8 7]


In [317]:
## 2D Array Slicing Row
print(a10)
print(a10[1,:])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[4. 5. 6. 7.]


In [318]:
## 2D Array Slicing Column
print(a10)
print(a10[:,1])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[1. 5. 9.]


In [319]:
## 2D Array Slicing Multiple Rows, Columns
print(a10)
print(a10[0:2,2:])
print(a10[::2,1::2])
print(a10[1:2,::3])
print(a10[:2,1::])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[2. 3.]
 [6. 7.]]
[[ 1.  3.]
 [ 9. 11.]]
[[4. 7.]]
[[1. 2. 3.]
 [5. 6. 7.]]


In [320]:
## 3D Array Slicing
print(a11)
# print(a11[1,:,1])
# print(a11[2,1:,1:])
print(a11[::2,0:1,::2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  2]]

 [[18 20]]]


## Iterating

In [321]:
for i in np.nditer(a11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## Reshaping

In [342]:
## reshape
arr_1 = np.int32(np.random.random(12)*100)
print(arr_1)

arr1_shape = np.array(arr_1).reshape(3,4)
arr1_shape

[83 31 47 31 84 11 91 43  7 27 52 89]


array([[83, 31, 47, 31],
       [84, 11, 91, 43],
       [ 7, 27, 52, 89]])

In [343]:
## transpose
np.transpose(arr1_shape)

array([[83, 84,  7],
       [31, 11, 27],
       [47, 91, 52],
       [31, 43, 89]])

In [344]:
## ravel (any ndim array will be 1D array)
np.ravel(arr1_shape)

array([83, 31, 47, 31, 84, 11, 91, 43,  7, 27, 52, 89])

## Stacking

In [346]:
## horizontal stacking
arr4 = np.arange(12).reshape(3,4)
arr5 = np.arange(12,24).reshape(3,4)

np.hstack((arr4, arr5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [348]:
## vertical stacking
np.vstack((arr4, arr5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [352]:
## horizontal splitting
np.hsplit(arr4, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
## verrizontal splitting
np.vsplit(arr4, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]