## Sort

In [85]:
## np.sort()
import numpy as np

arr1 = np.random.randint(1,100,50)
## asc
np.sort(arr1)

## dec
np.sort(arr1)[::-1]

array([96, 96, 92, 87, 87, 86, 86, 86, 86, 85, 85, 83, 80, 69, 68, 68, 67,
       66, 65, 64, 63, 60, 57, 53, 52, 49, 48, 46, 45, 44, 44, 43, 43, 41,
       40, 40, 37, 35, 34, 31, 31, 25, 21, 17, 15, 10,  7,  7,  5,  3])

## Append

In [86]:
## 1D
np.append(arr1, 500)

array([  3,  87,  68,   7,  48,  45,  43,   5,  57,  96,  44,  64,  63,
        87,  37,  10,  15,  69,  86,  86,  85,  34,  52,  92,  41,  21,
        44,  60,  83,  46,  25,  66,  49,  67,  86,  53,  17,  85,   7,
        31,  43,  40,  40,  31,  80,  35,  86,  65,  68,  96, 500])

In [87]:
## 2D
arr2 = np.random.randint(1,20,12).reshape(4,3)
np.append(arr2, np.int64(np.random.random((arr2.shape[0], 2))*100), axis=1)

array([[10, 14,  1, 69, 95],
       [19, 19,  6, 96, 50],
       [11,  6, 18,  0, 86],
       [ 9, 15,  3,  4, 42]], dtype=int64)

## Concate

In [88]:
## concatenate
arr3 = np.random.randint(1,20,12).reshape(4,3)
arr4 = np.random.randint(1,20,12).reshape(4,3)
np.concatenate((arr3, arr4), axis=1)

array([[12, 17,  5, 10, 13,  7],
       [ 7,  2,  4,  3, 13, 12],
       [10, 13,  9,  5,  4,  9],
       [ 3, 19, 19, 19, 10, 13]])

## Unique

In [89]:
## unique
arr5 = np.array([1,2,3,4,5,6,6,6,6,7,6,4,5,6])
np.unique(arr5)

array([1, 2, 3, 4, 5, 6, 7])

## Expand Dimension

In [90]:
## expand_dim
arr6 = np.arange(12)
np.expand_dims(arr6, axis=1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

## Where

In [91]:
## where => np.where(condition, true_value, false_value)
arr7 = np.random.randint(1, 100, 20)
np.where(arr7>20, 10, arr7)

array([10, 10, 10, 10, 10, 20, 10, 10,  9, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 11, 10])

## Arg max, min

In [92]:
## max
arr8 = np.random.randint(1, 100, 20)
np.argmax(arr8)

15

In [93]:
## min
arr8 = np.random.randint(1, 100, 20)
np.argmin(arr8)

16

## Cumulative

In [94]:
## cumsum
arr9 = np.array([1,2,3,4,5,6,6,6,6,7])
np.cumsum(arr9)

array([ 1,  3,  6, 10, 15, 21, 27, 33, 39, 46])

In [95]:
## cumprod
np.cumprod(arr9)

array([      1,       2,       6,      24,     120,     720,    4320,
         25920,  155520, 1088640])

## Percentile

In [96]:
## percentile
np.percentile(arr9, 10)

1.9

## More built in functions

In [97]:
## histogram
np.histogram(arr9, bins=[0,2,4,6,8,10])

(array([1, 2, 2, 5, 0], dtype=int64), array([ 0,  2,  4,  6,  8, 10]))

In [98]:
## corrcoef
arr10 = np.random.randint(1,100,10)
arr11 = np.random.randint(1,100,10)
np.corrcoef(arr10,arr11)

array([[ 1.        , -0.03438332],
       [-0.03438332,  1.        ]])

In [99]:
## isin
arr10[np.isin(arr10, arr11)]

array([42, 88])

In [100]:
## flip
np.flip(arr11)

array([42, 85, 26, 14, 64, 26, 61, 54, 88, 21])

In [101]:
## put => it will change the given array permanently => np.put(array, [index, idex], [replace_value, r_v)])
arr12 = np.array([3,45,5,6,7,8,54,3])
np.put(arr12, [1,6], [4,5])
arr12

array([3, 4, 5, 6, 7, 8, 5, 3])

In [102]:
## delete => np.delete(arr, [arr_index])
np.delete(arr12, 5)

array([3, 4, 5, 6, 7, 5, 3])

## Set functions

In [104]:
## union1d
np.union1d(arr10, arr11)

array([13, 14, 21, 26, 31, 41, 42, 54, 56, 61, 64, 66, 69, 74, 85, 88, 93])

In [105]:
## intersect1d
np.intersect1d(arr10, arr11)

array([42, 88])

In [106]:
## setxor1d
np.setxor1d(arr10, arr11)

array([13, 14, 21, 26, 31, 41, 54, 56, 61, 64, 66, 69, 74, 85, 93])

In [107]:
## in1d
arr10[np.in1d(arr10, arr11)]

array([42, 88])

In [108]:
## clip => it will return given range numbers
np.clip(arr10, a_min=10, a_max=50)

array([50, 50, 41, 31, 50, 42, 13, 50, 50, 50])